import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,dirname,basename} from 'node:path';
import {SqliteAuthStore} from '../src/data/auth-sqlite';
import {SqliteWorkspaceStore} from '../src/data/workspace-sqlite';
import {AuthService} from '../src/auth/service';
import {WorkspaceService} from '../src/workspaces/service';
import {AuthError} from '../src/auth/errors';
import {mockRepository} from '../src/data/mock-repository';
import {aggregate} from '../src/domain/metrics';
import {defaultGoals} from '../src/domain/preferences';
const secret=()=>randomBytes(24).toString('base64url');
const rejected=(status:number)=>(e:unknown)=>e instanceof AuthError&&e.status===status;
test('workspaces: migração, isolamento, metas, integrações, contas e atribuições',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'traffic-workspaces-'));const path=join(dir,'app.sqlite');const authStore=new SqliteAuthStore(path);const auth=new AuthService(authStore);const pass=secret();
 await auth.seedAdmin({name:'Administrador de teste',email:'admin@example.test',role:'admin',active:true},pass);const admin=(await auth.login('admin@example.test',pass)).token;
 const existing=await auth.createUser(admin,{name:'Gestor existente',email:'old@example.test',role:'manager',active:true},secret());
 const store=new SqliteWorkspaceStore(path);const service=new WorkspaceService(auth,store);let managerToken='';let managerId='';
 try{
 await t.test('migração preserva admin e vincula gestores antigos apenas ao workspace original',()=>{assert.equal(auth.requireAdmin(admin).name,'Administrador de teste');assert.equal(service.list(admin).length,3);assert.equal(store.hasMember('ws-scale',existing.id),true);assert.equal(store.hasMember('ws-loca',existing.id),false);const reopened=new SqliteWorkspaceStore(path);assert.equal(reopened.list().length,3);reopened.close();});
 await t.test('administrador cria, edita, valida slug e status',()=>{const w=service.save(admin,{name:'Nova operação',slug:'nova-operacao',active:true,timezone:'America/Sao_Paulo',currency:'BRL',description:''});assert.equal(service.list(admin).length,4);service.save(admin,{...w,active:false},w.id);assert.equal(service.requireAccess(admin,w.id).active,false);assert.throws(()=>service.save(admin,{...w,id:undefined}),rejected(409));assert.throws(()=>service.save(admin,{...w,slug:'nova-2',timezone:'invalido'}),rejected(400));});
 await t.test('novo gestor não recebe acesso implícito; vínculo libera só um workspace',async()=>{const p=secret();const manager=await auth.createUser(admin,{name:'Gestor restrito',email:'manager@example.test',role:'manager',active:true},p);managerId=manager.id;managerToken=(await auth.login(manager.email,p)).token;assert.equal(service.accessible(managerToken).length,0);service.setMembers(admin,'ws-loca',[managerId]);assert.deepEqual(service.accessible(managerToken).map(w=>w.id),['ws-loca']);assert.throws(()=>service.requireAccess(managerToken,'ws-scale'),rejected(403));assert.throws(()=>service.detail(managerToken,'ws-loca'),rejected(403));});
 await t.test('metas são persistidas por workspace e leitura/escrita cruzada é proibida',()=>{service.saveGoals(managerToken,'ws-loca',{...defaultGoals,maxCpl:72});assert.equal(service.goals(admin,'ws-loca').maxCpl,72);assert.equal(service.goals(admin,'ws-scale').maxCpl,40);assert.throws(()=>service.goals(managerToken,'ws-scale'),rejected(403));assert.throws(()=>service.saveGoals(managerToken,'ws-scale',defaultGoals),rejected(403));});
 await t.test('dados simulados pertencem ao contexto e mudam ao trocar de empresa',async()=>{const a=await mockRepository.getDataset(service.requireAccess(admin,'ws-scale'));const b=await mockRepository.getDataset(service.requireAccess(admin,'ws-loca'));for(const list of [a.campaigns,a.daily,a.creatives,a.leads,a.recommendations])assert.ok(list.every(r=>r.workspaceId==='ws-scale'));for(const list of [b.campaigns,b.daily,b.creatives,b.leads,b.recommendations])assert.ok(list.every(r=>r.workspaceId==='ws-loca'));assert.notEqual(aggregate(a.daily).spend,aggregate(b.daily).spend);assert.notEqual(a.campaigns[0]!.name,b.campaigns[0]!.name);});
 await t.test('integração começa desconectada, conecta três contas e não aceita ações do gestor',()=>{assert.equal(service.integrations(admin,'ws-loca').integrations.find(i=>i.provider==='meta')?.connected,false);service.metaAction(admin,'ws-loca','connect');const snapshot=service.integrations(managerToken,'ws-loca');assert.equal(snapshot.accounts.length,3);assert.equal(snapshot.integrations.find(i=>i.provider==='meta')?.simulated,true);assert.throws(()=>service.metaAction(managerToken,'ws-loca','disconnect'),rejected(403));assert.throws(()=>service.integrations(managerToken,'ws-scale'),rejected(403));service.metaAction(admin,'ws-loca','sync');assert.ok(service.integrations(admin,'ws-loca').accounts[0]!.lastSyncAt);});
 await t.test('conta só aceita gestor da equipe; remoção de membro limpa atribuição',()=>{const a=service.integrations(admin,'ws-loca').accounts.find(a=>a.active)!;service.updateAccount(admin,'ws-loca',a.id,{workspaceId:'ws-loca',syncEnabled:true,managerIds:[managerId]});assert.throws(()=>service.updateAccount(admin,'ws-loca',a.id,{workspaceId:'ws-loca',syncEnabled:true,managerIds:[existing.id]}),rejected(400));service.setMembers(admin,'ws-loca',[]);assert.equal(service.integrations(admin,'ws-loca').accounts.find(row=>row.id===a.id)?.managerIds.length,0);assert.throws(()=>service.integrations(managerToken,'ws-loca'),rejected(403));service.setMembers(admin,'ws-loca',[managerId]);});
 await t.test('transferência altera propriedade e bloqueia ID de conta de outro workspace',()=>{service.metaAction(admin,'ws-scale','connect');const a=service.integrations(admin,'ws-loca').accounts.find(a=>a.active)!;service.updateAccount(admin,'ws-loca',a.id,{workspaceId:'ws-scale',syncEnabled:true,managerIds:[]});assert.ok(!service.integrations(managerToken,'ws-loca').accounts.some(row=>row.id===a.id));assert.ok(service.integrations(admin,'ws-scale').accounts.some(row=>row.id===a.id));assert.throws(()=>service.updateAccount(admin,'ws-loca',a.id,{workspaceId:'ws-loca',syncEnabled:false,managerIds:[]}),rejected(404));});
 await t.test('desconectar preserva contas e desliga sincronização; inativar bloqueia gestor',()=>{service.metaAction(admin,'ws-loca','disconnect');const snapshot=service.integrations(admin,'ws-loca');assert.ok(snapshot.accounts.every(a=>!a.syncEnabled));assert.equal(snapshot.integrations.find(i=>i.provider==='meta')?.connected,false);const w=service.requireAccess(admin,'ws-loca');service.save(admin,{...w,active:false},w.id);assert.equal(service.accessible(managerToken).length,0);assert.throws(()=>service.goals(managerToken,w.id),rejected(403));assert.throws(()=>service.metaAction(admin,w.id,'connect'),rejected(409));});
 }finally{store.close();authStore.close();const absolute=resolve(dir);if(dirname(absolute)===resolve(tmpdir())&&basename(absolute).startsWith('traffic-workspaces-'))rmSync(absolute,{recursive:true,force:true});}
});
